# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroDaily',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('record_date', models.FloatField(blank=True, db_column='pomo_total', null=True)),
            ],
        ),
    ]
