# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfdata', '0002_pomodorodaily'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomodorodaily',
            options={'managed': False},
        ),
    ]
