# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfdata', '0003_auto_20171130_1021'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pomodorodaily',
            table='pomo_excel_daily',
        ),
    ]
