# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='last_seen',
            field=models.DateField(auto_now=True),
        ),
    ]
