# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfdata', '0004_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'managed': True},
        ),
    ]
