# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdata', '0005_auto_20171115_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomodoro',
            options={},
        ),
        migrations.RemoveField(
            model_name='mood',
            name='id',
        ),
        migrations.AlterField(
            model_name='mood',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
