# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdata', '0007_auto_20171115_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='id',
        ),
        migrations.AlterField(
            model_name='weight',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
