# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfdata', '0008_auto_20171115_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlefit',
            options={'managed': True},
        ),
    ]
