# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdata', '0009_auto_20171115_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlefit',
            name='id',
        ),
        migrations.AlterField(
            model_name='googlefit',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
